print("BIENVENIDO A MI TRIVIA DE ANATOMIA\n")
print ("Responder las siguientes preguntas,escribiendo la letra de la alternativa y presiona 'Entrer' para continuar:\n")

print ("1)¿Cuántos huesos tiene el cuerpo humano?")
print ("   a) 200")
print ("   b) 206")
print ("   c) 212")
print ("   d) 208")
respuesta_1=input("\n Tu respuesta: ")
print ("2)¿Cuántos diente tiene un adulto?")
print ("   a) 28")
print ("   b) 26")
print ("   c) 32")
print ("   d) 30")
respuesta_2=input("\nTu respuesta: ")
print ("3)¿Cómo se llama la capa exterior de la piel?")
print ("   a) Dermis")
print ("   b) Epidermis")
print ("   c) Hipodermis")
print ("   d) Folículo piloso")
respuesta_3=input("\nTu respuesta: ")
print ("4)¿Dónde comienza la digestión de los lípidos?")
print ("   a) Estómago")
print ("   b) Boca")
print ("   c) Esófago")
print ("   d) Duodeno")
respuesta_4=input("\nTu respuesta: ")
print ("5)¿las glándulas suprarrenales donde están ubicadas?")
print ("   a) Encima de los riñones ")
print ("   b) Debajo de los riñones")
print ("   c) Encima de la vejiga")
print ("   d) En la uretra")
respuesta_4=input("\nTu respuesta: ")
print ("6)¿Cuál es la hormona que secreta el páncreas?")
print ("   a) Urea")
print ("   b) Testosterona")
print ("   c) Insulina")
print ("   d) Bilis")
respuesta_6=input("\nTu respuesta: ")
print("Antes de terminar desearia saber tu nombre. ¿Cómo te llamas?")
tunombre=input()
print("♥ Gracias por jugar mi trivia "+ tunombre)